branches:
  only:
    - main
language: node_js
node_js:
  - 16

services:
  - docker

script:
  ## Build
  - docker-compose -f docker-compose-build.yaml build
  ## Tagging
  - docker tag udagram-api-feed hieupm165/udagram-api-feed:latest
  - docker tag udagram-api-user hieupm165/udagram-api-user:latest
  - docker tag udagram-frontend hieupm165/udagram-frontend:latest
  - docker tag reverseproxy hieupm165/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  ## Push
  - docker push hieupm165/udagram-api-feed
  - docker push hieupm165/udagram-api-user
  - docker push hieupm165/udagram-frontend
  - docker push hieupm165/reverseproxy
